services:
  bind9:
    image: ubuntu/bind9
    container_name: bind9
    environment:
      - TZ=Europe/Paris
    ports:
      - "53:53/udp"
    volumes:
      - "./config:/etc/bind"
    restart: unless-stopped
